### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by iammello** [Intevel/nuxt-directus#197]
i found only composables useDirectusFiles is only getFiles, getThumbnail.

I would like to upload image or file by this module

**Comment by Lucas-Gruber** [comment]
I really like this Idea! I would simplify the process so much.

**Comment by Sandros94** [comment]
Just to give an update so that developers are aware that we are working on this:

Currently there is a major rewrite of this module undergoing. This will unlock a number of feature requests, like this one, by taking advantage of the work done in the new Directus SDK that has been released last summer.

While the rewrite **shouldn't be used in production (yet)**, you could look at the current state in #215.

**Comment by casualmatt** [comment]
Closing issue: 
The feature request is available in the new module.
