### ISSUE TITLE
Options API?

### ISSUE THREAD

**Issue by adamkhan** [Intevel/nuxt-directus#247]
Hi,

Thanks for Nuxt-Directus and it's great to see development is ongoing. A question from what must be an aging brain that still prefers the Options API to the Composition API: there's nothing in the docs about how to use Nuxt-Directus in Options API — is it possible?

**Comment by casualmatt** [comment]
Hello @adamkhan,

We are working on the new V6 documentation, but our priority is to prepare examples and documentation for the composition api.
This is also because Nuxt itself uses the composition api in his documentation.

We will evaluate that when 6.0 is out and the full documentation will be done.
